version: 2.1
orbs:
    node: circleci/node@5.0.3
jobs:
  build:
    resource_class: medium # ここで指定
    working_directory: ~/repo
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm test